### ISSUE TITLE
Resource_Review Model

### ISSUE THREAD

**Issue by sasianan19** [RogueStorm7/mirror-mirror-WOW#18]
## Overview
Set up 'Resource_Review' as one-to-many with foreign key (Resource ID) in models.py 

## Technical Notes
Model has 5 attributes: 

- foreign key for Resource ID (int)
- text (str)
- source_review ID (int)
- date (date)
- stars (int)

Each review is for ONE resource

**Comment by jtc21am** [comment]
Form:


class ResourceReviewForm(forms.ModelForm):

    class Meta:
        model = ResourceReview
        fields = ["resourcereview_username","resourcereview_stars","resourcereview_comment"]
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['resourcereview_username'].label = 'Your Name:'
        self.fields['resourcereview_stars'].label = 'Stars'
        self.fields['resourcereview_comment'].label = 'Review:'

**Comment by jtc21am** [comment]
Model:
class ResourceReview(models.Model):
    """Review on a Resource"""
    resourcereview_comment = models.TextField(max_length=4000)
    resourcereview_username = models.CharField(max_length=4000)
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE)
    resourcereview_date = models.DateTimeField(auto_now_add=True)
    resourcereview_rating = (
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5)
    )
    resourcereview_stars = models.IntegerField(choices=resourcereview_rating)
    def __str__(self):
        return self.resource.title

**Comment by jtc21am** [comment]
Change ResourceTempPage Button for Review:
                    <div class="buttons-bubblecontainer">
                        <a class="button edit" href={% url 'resource rate' resource.id %}>Review</a>

**Comment by jtc21am** [comment]
Views:

class ResourceReviewDetailView(View):
    def get(self, request, resource_id):
        resource = Resource.objects.get(id=resource_id)
        form = ResourceReviewForm(initial={'resourcereview_comment': ResourceReview.resourcereview_comment, 'resourcereview_username': resourcereview.resourcereview_username,'resourcereview_rating':resourcereview_rating, 'resourcereview_stars': resourcereview_stars})
        
        return render(
            request=request, template_name='resourcereview.html', context={'form':form, 'id': resource_id})

    def post(self, request, resource_id):
        '''Update or delete the specific task based on what the user submitted in the form'''
        resourcereview = ResourceReview.objects.filter(id=resource_id)
        if 'save' in request.POST:
            form = ResourceReviewForm(request.POST)
            if form.is_valid():
                resourcereview_comment = form.cleaned_data['resourcereview_comment']
                resourcereview_username = form.cleaned_data['resourcereview_username']
                resourcereview_rating = form.cleaned_data['resourcereview_rating']
                resourcereview_stars = form.cleaned_data['resourcereview_stars']
                resourcereview.update(resourcereview_comment=resource_comment)
                resourcereview.update(resourcereview_username=resource_username)
                resourcereview.update(resourcereview_rating=resource_rating)
                resourcereview.update(resourcereview_stars=resource_stars)

        elif 'delete' in request.POST:
            resourcereview.delete()

        # "redirect" to the list page
        return redirect('resourcetemppage')

**Comment by jtc21am** [comment]
review rate.html
   <div>
        <h1>Resource review</h1>
    </div>
    <div>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <button  class=" btn btn-primary" type="submit">RATE NOW</button>
        </form>
    </div>
