### ISSUE TITLE
Comment Model

### ISSUE THREAD

**Issue by sasianan19** [RogueStorm7/mirror-mirror-WOW#20]
## Overview
Set up "Comment" model in models.py

## Technical Notes
Model has 3 attributes:

- date (date)
- text (str)
- comment ID (int)

**Comment by jtc21am** [comment]
Post, add note and update

**Comment by jtc21am** [comment]
Move Comment HTML to Review/Comment HTML

**Comment by jtc21am** [comment]
Completed
